### ISSUE TITLE
signin payload

### ISSUE THREAD

**Issue by ambou-97** [SuturaOrg/campus-sutura-api#2]
![1](https://user-images.githubusercontent.com/66280182/163730057-5881074f-f5c0-44d7-82fa-571f55250979.png)
Le programme ne voit pas l'attribut username
![2](https://user-images.githubusercontent.com/66280182/163730078-92485d8f-8a98-4227-9ec8-b91352029fc9.png)

**Comment by iib0011** [comment]
@ambou-97 username et password sont des pathVariables

**Comment by ambou-97** [comment]
donc l'URI doit être ceci: 
http://localhost:8080/auth/signin/admin/admin ?

**Comment by iib0011** [comment]
http://localhost:8080/auth/signin?username=admihn112&password=admin
